# Generated by Django 5.2 on 2025-04-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='articles/', verbose_name='تصویر')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='تاریخ قرارگیری در سایت')),
                ('write_time', models.DateField(verbose_name='زمان نوشتن ')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='متن')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
