# Generated by Django 5.2 on 2025-05-11 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='articles/game_comment/user_image', verbose_name='تصویر کاربر')),
                ('user_name', models.CharField(max_length=50, verbose_name='نام کاربری')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('content', models.TextField(verbose_name='متن نظر')),
                ('comment_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.article')),
            ],
            options={
                'verbose_name': 'نظر بازی',
                'verbose_name_plural': 'نظرات بازی',
            },
        ),
    ]
