# Generated by Django 5.2 on 2025-05-11 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_game_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_Comment',
            new_name='Article_Comment',
        ),
    ]
