# Generated by Django 5.2.1 on 2025-05-19 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_game_comment_article_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article_comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.RenameField(
            model_name='article_comment',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='article_comment',
            name='comment_article',
        ),
        migrations.RemoveField(
            model_name='article_comment',
            name='user_image',
        ),
        migrations.RemoveField(
            model_name='article_comment',
            name='user_name',
        ),
        migrations.AddField(
            model_name='article_comment',
            name='article',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='مقاله'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_comment',
            name='email',
            field=models.EmailField(default=34, max_length=254, verbose_name='پست الکترونیکی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='write_time',
            field=models.DateField(auto_now_add=True, verbose_name='زمان نوشتن '),
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='created_time',
            field=models.DateField(auto_now_add=True, verbose_name='زمان ایجاد نظر'),
        ),
    ]
