# Generated by Django 5.2.1 on 2025-05-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default=0, upload_to='profile/images/'),
            preserve_default=False,
        ),
    ]
