# Generated by Django 5.2 on 2025-04-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='AboutUs/team/image/', verbose_name='تصویر شخص')),
                ('name', models.CharField(max_length=50, verbose_name='نام شخص')),
                ('job', models.CharField(max_length=50, verbose_name='مهارت کاربر')),
                ('twitter_user_link', models.CharField(blank=True, max_length=50, null=True, verbose_name='لینک توییتر کاربر')),
                ('facebook_user_link', models.CharField(blank=True, max_length=50, null=True, verbose_name='لینک فیسبوک کاربر')),
                ('instagram_user_link', models.CharField(blank=True, max_length=50, null=True, verbose_name='لینک اینستاگرام کاربر')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم ها',
            },
        ),
    ]
