# Generated by Django 5.2.1 on 2025-05-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0002_contactus_created_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'ارتباط', 'verbose_name_plural': 'ارتباطات'},
        ),
    ]
