# Generated by Django 5.2 on 2025-04-10 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مسابقه')),
                ('content', models.TextField(verbose_name='توضیحات مسابقه')),
                ('competition_date', models.DateField(default=datetime.time(0, 0), verbose_name='تاریخ مسابقه')),
                ('video', models.FileField(blank=True, null=True, upload_to='Competitions/videos/%Y/%m/%d', verbose_name='ویدیو مسابقه')),
                ('image', models.ImageField(upload_to='Competitions/pictures/%Y/%m/%d', verbose_name='تصویر مسابقه')),
            ],
            options={
                'verbose_name': 'مسابقه',
                'verbose_name_plural': 'مسابقات',
            },
        ),
    ]
