# Generated by Django 5.2 on 2025-04-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Competition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='operating_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='توضیحات سیستم عامل')),
                ('Genre', models.CharField(max_length=50, verbose_name='ژانر بازی')),
                ('Image_quality', models.CharField(max_length=50, verbose_name='کیفیت تصویر')),
                ('number_of_people', models.CharField(choices=[('یک نفره', 'one person'), ('دو نفره', 'Two player'), ('چند نفره', 'multiplayer')], max_length=50, verbose_name='تعداد نفرات بازی')),
            ],
            options={
                'verbose_name': 'سیستم عامل',
                'verbose_name_plural': 'سیستم عامل ها',
            },
        ),
    ]
