# Generated by Django 5.2 on 2025-04-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Competition', '0002_operating_system'),
    ]

    operations = [
        migrations.DeleteModel(
            name='operating_system',
        ),
    ]
