# Generated by Django 5.2 on 2025-04-24 07:24

import Competition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Competition', '0003_delete_operating_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Competitions/videos/%Y/%m/%d', validators=[Competition.models.validate_file_extensions], verbose_name='ویدیو مسابقه'),
        ),
    ]
