# Generated by Django 5.2 on 2025-04-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_comment_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamenews',
            options={'verbose_name': 'خبر بازی', 'verbose_name_plural': 'اخبار بازی'},
        ),
        migrations.AddField(
            model_name='upcominggame',
            name='pic',
            field=models.ImageField(null=True, upload_to='Games/pictures/', verbose_name='تصویر بازی'),
        ),
    ]
