# Generated by Django 5.2 on 2025-04-24 07:57

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_gamenews_options_upcominggame_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pic',
            field=models.ImageField(null=True, upload_to='Games/game/images', verbose_name='تصویر بازی'),
        ),
        migrations.AlterField(
            model_name='upcominggame',
            name='icon',
            field=models.ImageField(upload_to='Games/icon/', validators=[games.models.validate_file_extensions], verbose_name='آیکون'),
        ),
    ]
