# Generated by Django 5.2 on 2025-04-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_pic_alter_upcominggame_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pic',
            field=models.ImageField(null=True, upload_to='Games/images', verbose_name='تصویر بازی'),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='comment_count',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تعداد نظر'),
        ),
    ]
