# Generated by Django 5.2.1 on 2025-06-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_pic_alter_gamenews_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name_slu',
            field=models.SlugField(default=0, verbose_name='نام لاتین بازی'),
            preserve_default=False,
        ),
    ]
