# Generated by Django 5.2.1 on 2025-06-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_name_slu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name_slu',
            new_name='gallery_type',
        ),
    ]
